name: Backup GitHub Repositories

on:
  schedule:
    - cron: '0 0 * * *'  # Run the workflow daily, adjust the cron expression as needed

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Backup Repositories
      run: |
        BACKUP_DIR=backup_$(date '+%Y%m%d%H%M%S')
        mkdir $BACKUP_DIR
        for repo in $(gh repo list --json name --limit 10); do
          gh repo clone $repo $BACKUP_DIR/$repo
        done
        tar -czvf $BACKUP_DIR.tar.gz $BACKUP_DIR

    - name: Upload Backup to S3
      run: |
        aws s3 cp $BACKUP_DIR.tar.gz s3://${{ secrets.S3_BUCKET_NAME }}/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
